// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductWeb.API.Infrastructure.Data;

#nullable disable

namespace ProductWeb.API.Migrations
{
    [DbContext(typeof(ProductWebDbContext))]
    partial class ProductWebDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProductWeb.API.Core.Entities.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ID");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Introducing the only foundation a girl will ever need for a Matte Golden Complexion!",
                            Image = "/Images/TNK-foundation-3.jpg",
                            Name = "Thanakha Perfect Liquid to Powder Foundation",
                            Price = 11500m
                        },
                        new
                        {
                            ID = 2,
                            Description = "Thanakha Loose Mineral Powder weightlessly locks in make-up for perfect long-lasting wear with a flawless, pore-less finish creating a modern, velvety matte look with a touch of sheer coverage, while Natural Thanakha essence absorbs excess oil allowing you to be Selfie Perfect and HD ready all day.",
                            Image = "/Images/Thanakha Powder Pact.png",
                            Name = "Thanakha Powder Pact",
                            Price = 8690m
                        },
                        new
                        {
                            ID = 3,
                            Description = "our skin will look and feel radiant, refreshed, and soft - so you wake up with soft, glowing skin! ",
                            Image = "/Images/Thanakha Water Recharging Sleeping Mask - Night Cream - Old.jpg",
                            Name = "Thanakha Water Recharging Sleeping Mask - Night Cream - Old",
                            Price = 11500m
                        },
                        new
                        {
                            ID = 4,
                            Description = "Makeup palette collaboration with Moguk Pauk Pauk, leading fashion designer and makeup artist.",
                            Image = "/Images/Perfect Look in a Palette.jpeg",
                            Name = "Perfect Look in a Palette",
                            Price = 6550m
                        },
                        new
                        {
                            ID = 5,
                            Description = "Rejuvenate and refresh your spirit with a spritz of Bella Perfumes. Easy to carry, travel-friendly size.",
                            Image = "/Images/Perfume.jpeg",
                            Name = "Perfume",
                            Price = 5950m
                        },
                        new
                        {
                            ID = 6,
                            Description = "Foundation fit for a Superstar – specially made for Superstars who need to look perfect all day and night.",
                            Image = "/Images/Superstar Perfect Matte Foundation.png",
                            Name = "Superstar Perfect Matte Foundation",
                            Price = 14500m
                        },
                        new
                        {
                            ID = 7,
                            Description = "Suitable for All Skin Types.Alcohol-Free. Paraben-Free.",
                            Image = "/Images/Bella Serum Sheet Mask.jpeg",
                            Name = "Bella Serum Sheet Maskn",
                            Price = 2050m
                        },
                        new
                        {
                            ID = 8,
                            Description = "Wake up to juicy skin: nourished, renewed, glowing.",
                            Image = "/Images/Watermelon Jelly Night Cream.jpeg",
                            Name = "Watermelon Jelly Night Cream",
                            Price = 11500m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
